language: node_js
node_js:
  - 4.1
  - 4.2
  - 5.0
  - 5.1
os:
  - linux
sudo: false
before_install: npm install -g grunt-cli babel-cli
install: npm install
#before_script:
#script:
#after_success:
#after_failure:
#after_script:
